services:
  backend:
    build: ./backend
    container_name: test-scano-backend
    ports:
      - "127.0.0.1:8001:8000"
    volumes:
      - ./geoip:/geoip:ro
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: test-scano-frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend
    restart: unless-stopped

